// src/components/GenreFilter.vue
<template>
  <div class="mb-8">
    <h3 class="text-lg font-semibold mb-3 text-white">Filtrer par genre</h3>
    <div class="flex flex-wrap gap-2">
      <button
        v-for="genre in genres"
        :key="genre.id"
        @click="toggleGenre(genre.id)"
        :class="[
          'px-4 py-2 rounded-full text-sm font-medium transition-colors',
          selectedGenres.includes(genre.id)
            ? 'bg-primary-600 text-white'
            : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
        ]"
      >
        {{ genre.name }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Genre } from '@/types';

const props = defineProps<{
  genres: Genre[];
  selectedGenres: number[];
}>();

const emit = defineEmits<{
  (e: 'update:selected', value: number[]): void;
}>();

const toggleGenre = (genreId: number) => {
  const selected = [...props.selectedGenres];
  const index = selected.indexOf(genreId);
  
  if (index === -1) {
    selected.push(genreId);
  } else {
    selected.splice(index, 1);
  }
  
  emit('update:selected', selected);
};
</script>

// src/components/GenreFilter.tsx
import React from 'react';
import { Genre } from '../types/tmdb';

interface GenreFilterProps {
  genres: Genre[];
  selectedGenres: number[];
  onGenreToggle: (genreId: number) => void;
}

export const GenreFilter: React.FC<GenreFilterProps> = ({ genres, selectedGenres, onGenreToggle }) => {
  return (
    <div className="mb-8">
      <h3 className="text-lg font-semibold mb-3">Filtrer par genre</h3>
      <div className="flex flex-wrap gap-2">
        {genres.map((genre) => (
          <button
            key={genre.id}
            onClick={() => onGenreToggle(genre.id)}
            className={`px-4 py-2 rounded-full text-sm font-medium transition-colors
              ${selectedGenres.includes(genre.id)
                ? 'bg-blue-600 text-white'
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
          >
            {genre.name}
          </button>
        ))}
      </div>
    </div>
  );
};
